Entities setup/Gems
BDanyil/Library pull request #1
Opened 2021-03-15 22:21 UTC by BDanyil

2021-04-20 16:58 UTC, bl0rch1d requested changes
First wave of comments arrived 🚀

2021-04-20 16:58 UTC, bl0rch1d commented on .rubocop.yml
> +  Enabled: false
Add empty line, please:
A brief description of what this error means:
https://thoughtbot.com/blog/no-newline-at-end-of-file

2021-04-20 16:58 UTC, bl0rch1d commented on .ruby-version 
> +ruby 2.7.2
the same as above

2021-04-20 16:58 UTC, bl0rch1d commented on autoload.rb
> +require 'pry'
You can remove it from autoloader if it useless in code

2021-04-20 16:58 UTC, bl0rch1d commented on entities/author.rb
> +    raise ::StandardError, 'Name is required' if name.strip.empty?
Let's move this and similar validations to the module

2021-04-20 16:58 UTC, bl0rch1d commented on entities/author.rb
> +    raise ::StandardError, 'Name is required' if name.strip.empty?
`title.strip.empty?` repeated several times in your validations

2021-04-20 16:58 UTC, bl0rch1d commented on entities/book.rb
> +    raise ::StandardError, 'Must be an instance of Author class' unless author.instance_of? ::Author
The same as comment above but for instance validation. I see 3 places where similar validation happens

2021-04-20 16:58 UTC, bl0rch1d commented on extentions/data_builder.rb
> +module DataBuilder
Let's make a callable service instead of just module. You can

Short example of callable services. (More briefly you can read in google)
```ruby
class FakeDataGenerator
  class << self
    def call
      create_arrays
      generate_data
    end

    private

    # Implementation methods
  end
end
```

2021-04-20 16:58 UTC, bl0rch1d commented on extentions/db.rb
> +    File.open('library.yml', 'w') { |file| file.write(to_yaml) }
please, move 'library.yml' string to constant. It repeats several times

2021-04-20 16:58 UTC, bl0rch1d commented on extentions/statistics.rb
> +
1. `max_by` argument must be configurable by user
2. `orders_grouped = orders.group_by(&:reader)` and `orders_grouped = orders.group_by(&:book)` are the same algorithmic model, so you can move it to separate method and just pass `group_by` argument book or reader
3. `orders_grouped.max_by(3) { |_k, v| v.count }.map(&:first)` used several times. Can also be moved to separate method.
4. `_k`, `v` not a valid variable names. Please, use more descriptive names. The same about `tab` variable.
5. `orders_grouped` - заказы сгруппированы 👽

2021-04-21 08:22 UTC, BDanyil commented on .rubocop.yml
> +  Enabled: false
+

2021-04-21 08:22 UTC, BDanyil commented on .ruby-version 
> +ruby 2.7.2
+

2021-04-26 19:13 UTC, bl0rch1d commented on .rubocop.yml
> +
last line, please

2021-04-26 19:14 UTC, bl0rch1d commented on autoload.rb
> +require 'pry'
remove pry please

2021-04-27 06:56 UTC, bl0rch1d commented on extentions/db.rb
> +  STORAGE = 'library.yml'
STORAGE -> STORAGE_NAME

2021-04-27 06:58 UTC, bl0rch1d commented on extentions/validations.rb
> +  def check_instance(main, child, parent)
What are `main`, `child` and `parent` stands for? Please, more descriptive names for arguments and variables. Variable or argument name should briefly describe entity/data/action by itself

2021-04-27 06:59 UTC, bl0rch1d commented on extentions/statistics.rb
> +  def get_top(quantity, entity, filter, put)
What is `put` stands for? Please, more descriptive names for arguments and variables. Variable or argument name should briefly describe entity/data/action by itself

2021-04-27 07:05 UTC, bl0rch1d commented on .rubocop.yml
> +  Max: 20
Please, make 10

2021-04-27 07:07 UTC, bl0rch1d commented on entities/reader.rb
> +    @house = house
If method is too long you can move validation to a separate method ```validate```

2021-04-27 07:10 UTC, bl0rch1d commented on extentions/db.rb
> +    File.open(STORAGE, 'w') { |file| file.write(to_yaml) }
How this method works?

2021-04-27 07:11 UTC, bl0rch1d commented on extentions/db.rb
> +  end
How this method works?

2021-04-27 07:12 UTC, bl0rch1d commented on extentions/db.rb
> +end
Move these methods under private modifier. User shouldn't have access to direct storage modification

2021-04-27 07:33 UTC, bl0rch1d commented
Please, use the imperative mood and more brief message in commit. Such commits as:
```empty lines```, ```typo```, ```Top book/reader. Storage module for yaml``` and your other commit names are not acceptable and may became incomprehensible when you will merge it to master. Project may have a lot of commits and developers and all of them must follow the same commit conventions to achieve proper commits story. For example, you have ```Top book/reader. Storage module for yaml``` commit and I don't understand what was done within, maybe only you can understand it, but other developers can't and in future you may forget what the heck was done here. Yes, you can inspect it and see what was changed, but imagine if you will have a big project with million lines of code and thousands of commits in a such style 😄 

Examples:
```empty lines``` -> ```Remove empty lines```
```type``` -> ```Fix typo```

There are condensed rules:
1. Starting from capital letter
2. Imperative mood
3. Not longer then 72 symbols

2021-04-27 18:52 UTC, bl0rch1d commented on autoload.rb
> +require 'pry'
Remove pry, please

2021-04-27 18:53 UTC, bl0rch1d commented on extentions/db.rb
> +  end
How this method works?

2021-04-27 18:53 UTC, bl0rch1d commented on extentions/db.rb
> +  end
Why you created a new methods to call the same methods? What the goal?

2021-04-28 17:37 UTC, bl0rch1d approved these changes

2021-04-28 20:22 UTC, merged